name: 03 Basics Events Filters

on:
#  pull_request:
#    types: [closed,reopened]
##     two ways list
#      - closed
#      - reopened
  push:
#    branches:
#      - main
#      - saad
#    or same
#     branches: [main,saad]
#    ------------
#    branches-ignore:
#      - saad
#     -----------
#    tags:
#      - "v2"
#    tags-ignore:
#      - "v2"

#    paths:
#      - 'routes/web.php'
#      - routes/*.php'    one level files only
#      - routes/**.php'   multi level files and folder
#    paths-ignore:
#      - 'routes/console.php'
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: run hello world
        run: echo "hello world"
