name: 03 Basics Events Filters

on:
#  pull_request:
#    types: [closed,reopened]
##     two ways list
#      - closed
#      - reopened
  push:
    branches:
      - main
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: run hello world
        run: echo "hello world"
